use std::collections::HashMap;
use std::sync::OnceLock;

use egui::{Color32, Context, Id, Painter, Pos2, Rect, TextureHandle, TextureOptions};

/// Color emoji, drawn as sprites rather than text.
///
/// egui's text rasterizer has no color-glyph support, so no font we could
/// load will ever produce a colored emoji -- the COLRv1 fonts that ship on
/// Linux and Windows can't be rasterized by it at all, and the monochrome
/// outline font we bundle for fallback is, by definition, monochrome. The
/// only way to get color is to stop drawing emoji as glyphs.
///
/// So they're pre-rendered offline into one sprite atlas (see
/// `tools/gen_emoji_atlas.py`) and drawn here as textured quads. One
/// texture covers the whole picker set, so this costs a single upload and
/// no per-emoji state.
///
/// Anything outside the curated set -- an emoji typed into a label, or one
/// that came in from a scraped board -- isn't in the atlas and falls back
/// to the monochrome font path (see `super::fonts`). That's why every
/// entry point here returns a bool/Option rather than drawing something
/// wrong: callers are expected to fall back to text.
const ATLAS_PNG: &[u8] = include_bytes!("../../assets/emoji/atlas.png");
const ATLAS_INDEX: &str = include_str!("../../assets/emoji/atlas.txt");

struct Index {
    cols: usize,
    rows: usize,
    slots: HashMap<String, usize>,
}

fn index() -> &'static Index {
    static INDEX: OnceLock<Index> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut cols = 16usize;
        let mut slots = HashMap::new();
        let mut n = 0usize;

        for line in ATLAS_INDEX.lines() {
            if let Some(v) = line.strip_prefix("cols=") {
                cols = v.trim().parse().unwrap_or(16);
            } else if line.starts_with("cell=") || line.is_empty() {
                // `cell` only matters to the generator: positions here are
                // normalized UVs, so the pixel size is irrelevant.
            } else {
                slots.insert(line.to_string(), n);
                n += 1;
            }
        }

        let rows = n.div_ceil(cols.max(1)).max(1);
        Index { cols: cols.max(1), rows, slots }
    })
}

/// UV rect of `emoji` within the atlas, or `None` if it isn't in the
/// curated set.
fn uv(emoji: &str) -> Option<Rect> {
    let idx = index();
    // Fall back to a match with the emoji-presentation selector (U+FE0F)
    // stripped: the same emoji can be spelled with or without it, and a
    // label that came from outside the picker may not carry it.
    let slot = idx
        .slots
        .get(emoji)
        .or_else(|| idx.slots.get(emoji.replace('\u{fe0f}', "").as_str()))?;

    let (col, row) = (slot % idx.cols, slot / idx.cols);
    let (w, h) = (idx.cols as f32, idx.rows as f32);
    Some(Rect::from_min_max(
        Pos2::new(col as f32 / w, row as f32 / h),
        Pos2::new((col + 1) as f32 / w, (row + 1) as f32 / h),
    ))
}

/// The atlas texture, decoded and uploaded once and then kept in egui's
/// memory for the life of the process.
fn texture(ctx: &Context) -> Option<TextureHandle> {
    let id = Id::new("emoji_atlas");
    if let Some(cached) = ctx.data(|d| d.get_temp::<Option<TextureHandle>>(id)) {
        return cached;
    }

    let loaded = match image::load_from_memory(ATLAS_PNG) {
        Ok(img) => {
            let img = img.to_rgba8();
            let size = [img.width() as usize, img.height() as usize];
            let color = egui::ColorImage::from_rgba_unmultiplied(size, img.as_raw());
            Some(ctx.load_texture("emoji_atlas", color, TextureOptions::LINEAR))
        }
        Err(e) => {
            log::error!("could not decode bundled emoji atlas: {e}");
            None
        }
    };

    ctx.data_mut(|d| d.insert_temp(id, loaded.clone()));
    loaded
}

/// Draws `emoji` in color, centered in `rect`. Returns `false` if it isn't
/// in the atlas, in which case the caller should draw it as text instead.
pub fn paint(ctx: &Context, painter: &Painter, rect: Rect, emoji: &str) -> bool {
    let (Some(uv), Some(tex)) = (uv(emoji), texture(ctx)) else { return false };
    painter.image(tex.id(), rect, uv, Color32::WHITE);
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The atlas is generated by a script that has to be run by hand, so
    /// nothing stops someone adding an emoji to the picker and forgetting
    /// to regenerate. The failure mode would be silent -- that emoji
    /// quietly falls back to a monochrome glyph -- so it's worth a test.
    #[test]
    fn every_picker_emoji_is_in_the_atlas() {
        let missing: Vec<_> = super::super::emoji_picker::EMOJIS
            .iter()
            .filter(|e| uv(e).is_none())
            .collect();
        assert!(
            missing.is_empty(),
            "{} picker emoji missing from the atlas: {missing:?}\n\
             run `python3 tools/gen_emoji_atlas.py` to regenerate",
            missing.len()
        );
    }

    #[test]
    fn uvs_stay_inside_the_atlas() {
        for emoji in super::super::emoji_picker::EMOJIS {
            let rect = uv(emoji).expect("covered by the test above");
            assert!(
                rect.min.x >= 0.0 && rect.min.y >= 0.0 && rect.max.x <= 1.0 && rect.max.y <= 1.0,
                "{emoji} has out-of-range uv {rect:?}"
            );
        }
    }
}

/// An `Image` widget for `emoji`, for use in buttons and other widget
/// layouts where a raw painter call wouldn't participate in layout.
pub fn image(ctx: &Context, emoji: &str, size: f32) -> Option<egui::Image<'static>> {
    let (uv, tex) = (uv(emoji)?, texture(ctx)?);
    Some(
        egui::Image::new(egui::load::SizedTexture::new(tex.id(), egui::Vec2::splat(size)))
            .uv(uv)
            .fit_to_exact_size(egui::Vec2::splat(size)),
    )
}
